const json = {
  formOne: {
    company: {
      id: "16aca29a-1804-4d22-a6c2-f278b1c4857c",
      name: "FERROPINTURAS TORRE FUERTE SAS",
      region: "5df5fda2-3e1e-4943-8e5a-12832bd4a11e",
      address: "CL 21D 28E 6 20",
      sap_code: "70021248",
      telephone: "0",
      region_name: "VALLE DEL CAUCA",
      municipality: "dfd59470-9a27-4a29-9292-c0c153ed1804",
      search_company: "FERROPINTURAS TORRE FUERTE SAS NIT.901272193",
      municipality_name: "CALI",
      number_identification: "1234567890",
    },
    project: {
      id: "dc643561-0bf2-41ff-a488-9d2d199a9ed1",
      name: "MANZANARES",
      zone: {id: "bf8fa7c5-3bee-4810-973b-5bb29c73c43d", name: "U"},
      offerer: "CONSTRUCTORA BOLIVAR CALI S A",
      solution_modality: {
        id: "66ccb06c-c9d5-426b-80c9-807bf8400ea3",
        name: "Adquisicion de vivienda",
      },
    },
    headName: "PASTOR",
    ownerName: "CONSTRUCTORA BOLIVAR CALI S A",
    headGender: {
      id: "cea6c913-db58-4c42-a228-51546d0926fc",
      name: "Masculino",
    },
    companyName: "",
    homeAddress: {
      id: "",
      mainRoad: {
        id: "f2fbbe7e-33de-4a3f-b7cf-74988f8e8819",
        name: "Calle",
      },
      roadNumber: "28",
      fullAddress: "Calle 121 D  28 E 1 35 piso dos  ",
      suffixLetter: {
        id: "7d517570-5372-4bc3-a728-25ef32b2f96b",
        name: "E",
      },
      otherFeatures: "",
      mainRoadLetter: {
        id: "67c8bb6d-926f-4ff4-b2c0-fea1cc69198e",
        name: "D",
      },
      mainRoadNumber: "121",
      propertyNumber: "1 35 piso dos ",
      sectorIdentification: "",
    },
    workAddress: {
      id: "",
      mainRoad: {id: "", name: ""},
      roadNumber: "",
      fullAddress: "",
      suffixLetter: {id: "", name: ""},
      otherFeatures: "",
      mainRoadLetter: {id: "", name: ""},
      mainRoadNumber: "",
      propertyNumber: "",
      sectorIdentification: "",
    },
    headLastName: "betancourt",
    homeLocation: {
      id: "0b88aa0b-31ed-417e-a852-963629ebfe0c",
      name: "CALI, VALLE DEL CAUCA, Colombia",
    },
    homePhoneOne: "3163868651",
    homePhoneTwo: "",
    workLocation: {id: "", name: ""},
    workPhoneOne: "",
    workPhoneTwo: "",
    headBirthDate: "1994-09-23",
    headHousehold: "",
    headMntIncome: "1750000",
    companyAddress: {
      id: "",
      mainRoad: {id: "", name: ""},
      roadNumber: "",
      fullAddress: "",
      suffixLetter: {id: "", name: ""},
      otherFeatures: "",
      mainRoadLetter: {id: "", name: ""},
      mainRoadNumber: "",
      propertyNumber: "",
      sectorIdentification: "",
    },
    headOccupation: {
      id: "60a08a8b-cc8e-4238-b0f7-e37176cb8b1d",
      name: "Empleado",
    },
    headTpDocument: {
      id: "46dc2e93-a62a-48eb-b51c-ca8c3d38dcd4",
      name: "Cedula de ciudadanÃ­a",
    },
    companyLocation: "",
    headCivilStatus: {
      id: "87b63b54-e6f6-4a1d-89ed-a8e2c400d8ee",
      name: "Casado (a)",
    },
    headTpPostulant: {
      id: "988513ca-7ec7-4226-9e2c-37141c771657",
      name: "Ninguno",
    },
    headRelationship: "Jefe hogar",
    homeNeighborhood: "tercermilenio",
    companyAddressNew: "CL 21D 28E 1 35",
    companyLocationNew: "CALI, VALLE DEL CAUCA",
    headSpecialCondition: {
      id: "454d0f7a-908f-4540-9ecb-f2f78870247d",
      name: "Ninguna",
    },
    headNumberIdentification: "1234567890",
  },
  formTwo: {
    formItem: [
      {
        id: "8f6a635d-5eb4-4d87-ba3c-44cdb1b7a245",
        name: "Jazmin",
        gender: {
          id: "b0b0cd36-f4e0-4419-aa91-ba34d967e2c3",
          name: "Femenino",
        },
        lastName: "Barreto Chaux",
        birthDate: "1997-10-14",
        mntIncome: "0",
        occupation: {
          id: "58a8bdbc-07af-4924-a510-fac68f73bf10",
          name: "Hogar",
        },
        tpDocument: {
          id: "46dc2e93-a62a-48eb-b51c-ca8c3d38dcd4",
          name: "Cedula de ciudadanÃ­a",
        },
        civilStatus: {
          id: "87b63b54-e6f6-4a1d-89ed-a8e2c400d8ee",
          name: "Casado (a)",
        },
        tpPostulant: {
          id: "988513ca-7ec7-4226-9e2c-37141c771657",
          name: "Ninguno",
        },
        relationship: {
          id: "98ab3a94-ce58-400f-8dd2-ec3340634084",
          name: "CÃ³nyuge",
        },
        headHousehold: "",
        specialCondition: {
          id: "454d0f7a-908f-4540-9ecb-f2f78870247d",
          name: "Ninguna",
        },
        numberIdentification: "1144203870",
      },
    ],
    incomeEnd: 2,
    incomeStart: 0,
    totalMonthlyIncome: 1750000,
  },
  formFour: {
    vlSFV: 30,
    vlBudget: "",
    vlNewHome: "95000000",
    lotOwnerName: "",
    deepRegisDate: "",
    vlLotCadastral: "",
    solutionModality: {
      id: "66ccb06c-c9d5-426b-80c9-807bf8400ea3",
      name: "Adquisicion de vivienda",
    },
    requestedSubsidyVl: "30000000",
    solutionModalityCity: {
      id: "0b88aa0b-31ed-417e-a852-963629ebfe0c",
      name: "CALI, VALLE DEL CAUCA, Colombia",
    },
    totalPreviousSavings: 9503000,
    realEstateRegisNumber: "",
    totalHousingFinancing: "95000000",
    numberIdentificationOwner: "",
    totalVlOwnSiteConstruction: "0",
    otherComplementaryResources: 55497000,
    solutionModalityNeighborhood: "Manzanares ciudad del Valle 22",
  },
  formThree: {
    downPaymentVl: "",
    approvedCredit: "",
    AnotherResources: "",
    preApprovedCredit: "55497000",
    contributionLandVl: "",
    scheduledSavingsVl: "",
    severancePackageVl: "",
    contributionlaborVl: "",
    periodicFirstPayment: "2020-11-11",
    donationOtherEntities: "",
    scheduledSavingsVlTwo: "",
    contractualOpeningDate: "",
    downPaymentFirstPayment: "",
    periodicCapturingEntity: {
      id: "da7b4c45-fa7d-4e4f-bcad-703b4dd7c738",
      name: "ALIANZA FIDUCIARIA S.A",
    },
    periodicContributionsVl: "9503000",
    scheduledSavingsVlThree: "",
    solidarityContributions: "",
    contractualAccountNumber: "",
    periodicCertificationDate: "2022-06-09",
    periodicFirstPaymentThree: "",
    contractualCapturingEntity: {id: "", name: ""},
    downPaymentCapturingEntity: "",
    periodicCapturingEntityTwo: {id: "", name: ""},
    periodicContributionsVlTwo: "",
    scheduledSavingsOpeningDate: "",
    contractualCertificationDate: "",
    downPaymentCertificationDate: "",
    periodicCapturingEntityThree: {id: "", name: ""},
    periodicCertificationDateTwo: "",
    periodicContributionsVlThree: "",
    contractualscheduledSavingsVl: "",
    dateCreditApprovedPreApproved: "2022-06-10",
    scheduledSavingsAccountNumber: "",
    territorialEntityContribution: "",
    periodicCertificationDateThree: "",
    scheduledSavingsOpeningDateTwo: "",
    entityCreditApprovedPreApproved: "DAVIVIENDA",
    scheduledSavingsCapturingEntity: {id: "", name: ""},
    severancePackageCapturingEntity: {id: "", name: ""},
    scheduledSavingsAccountNumberTwo: "",
    scheduledSavingsOpeningDateThree: "",
    scheduledSavingsCertificationDate: "",
    severancePackageCertificationDate: "",
    scheduledSavingsAccountNumberThree: "",
    scheduledSavingsCapturingEntityTwo: {id: "", name: ""},
    severancePackageImmobilizationDate: "",
    scheduledSavingsCapturingEntityThree: {id: "", name: ""},
    scheduledSavingsCertificationDateTwo: "",
    scheduledSavingsCertificationDateThree: "",
  },
};

export default json;
